# Generated by Django 2.2.3 on 2019-08-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='code',
            field=models.CharField(default='sa', max_length=32),
            preserve_default=False,
        ),
    ]
