# Generated by Django 2.2.3 on 2019-08-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190812_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='r',
            field=models.ManyToManyField(to='app01.Host'),
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
