#!/bin/sh
# 时间：2019-06-25
# 编写人：此脚本是获取windows server 2012系统下当前远程连接的用户有哪些

[ -f "/mnt/monitor_data/centreon/show_user_status.txt" ] && rm -rf /mnt/monitor_data/centreon/show_user_status.txt


ansible 192.168.0.85 -m win_shell -a 'query USER' >/tmp/1.txt

administrator="夏天"
lixianhu="李现虎"
lijingjing="李晶晶"
qiyanqing="齐燕青"


for i in `cat /tmp/1.txt |grep "Active"|awk '{print $1}'`;do
        if [ $i == "administrator" ];then
		echo -e "外网虚拟机(192.168.0.85)当前连接的用户为:\033[32m $administrator  \033[0m"
        elif [ $i == "lixianhu" ];then
		echo -e "外网虚拟机(192.168.0.85)当前连接的用户为:\033[32m $lixianhu  \033[0m"
        elif [ $i == "lijingjing" ];then
		echo -e "外网虚拟机(192.168.0.85)当前连接的用户为:\033[32m $lijingjing  \033[0m"
        elif [ $i == "qiyanqing" ];then
		echo -e "外网虚拟机(192.168.0.85)当前连接的用户为:\033[32m $qiyanqing  \033[0m"
        fi
done
exit 0
